"""Add message_id to feedback

Revision ID: 89f7fe29db2b
Revises: f2f887443e1f
Create Date: 2025-09-18 22:26:00.065513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f7fe29db2b'
down_revision: Union[str, Sequence[str], None] = 'f2f887443e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'message_id')
    # ### end Alembic commands ###
